### ISSUE TITLE
Credit Issue

### ISSUE THREAD

**Issue by sidangvn** [adheeshenoy/Alan-SmartMirror-2020#15]
Hi there,

Thank you all for keep working on the Smart Mirror project under the ACM organization. My name is Si Dang [https://www.linkedin.com/in/sidang/] who gave the project to ACM in Spring 2018 when  Hitarthi was the president of the club. She agreed that all credits of the project will go to my team (Si Dang (USF Alumni), Karishma (USF Alumni), Krishna (USF Alumni), and Davin Hill (USF Alumni)). I believed that this project is under the control of ACM so the credits should be gone to our team. 

Thank you and let us know about the issue!
Si Dang

**Comment by adheeshenoy** [comment]
Due to the confusion, I have renamed the repo.
